### ISSUE TITLE
saga gis 2.3.2 commands are not installed in qgis flatpak 3.2

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.qgis.qgis#10]
All commands saga gis are not installed in qgis flatpak 3.2.3
Windows version has them by default
Saga Gis 2.3.2 is not packaged
It should  look like this 
![saga gis](https://user-images.githubusercontent.com/29207169/46172659-49c40700-c261-11e8-9a61-3b9e68440f82.png)

**Comment by Lvaskz** [comment]
any progress?

**Comment by aleixpol** [comment]
Hi, I am aware of this issue, I'm just busy this week. I actually put some work towards getting saga built but it didn't seem to be found afterwards. I need to sit down and understand what is happening at this point.

**Comment by Lvaskz** [comment]
Ok, thanks for your efforts and dedication.
I will go on waiting.

**Comment by Lvaskz** [comment]
Hi, when can we see this changes in qgis?

**Comment by aleixpol** [comment]
You should already have it as you update. I've had reports from people telling it works for them, so it should be working.

**Comment by Lvaskz** [comment]
Hi, I will try tonight. I will update with "flatpak update"

**Comment by Lvaskz** [comment]
Hi, I updated it and Saga commands are not installed, I reinstalled it but same issues.

**Comment by Lvaskz** [comment]
no menu saga gis
![ksnip_20181013-235017](https://user-images.githubusercontent.com/29207169/46913063-4019ef00-cf43-11e8-8172-2cd60b6401da.png)

**Comment by aleixpol** [comment]
It's apparently not working, some digging into the issue would be welcome.

**Comment by Lvaskz** [comment]
Well, now is working with last updated to qgis 3.4. Thanks. I think you should close.
