### ISSUE TITLE
site https://qgis.org// | '--command=pip3' | "pip3: No such file or directory"

### ISSUE THREAD

**Issue by Ricky-Tigg** [flathub/org.qgis.qgis#104]
**Reference:** [page](https://qgis.org/en/site/forusers/alldownloads.html#flatpak); **Object**: "`flatpak run --command=pip3 org.qgis.qgis install urllib3 --user`"

```
$ flatpak --command=pip3 run org.qgis.qgis --user install urllib3
bwrap: execvp pip3: No such file or directory
```

**Comment by aleixpol** [comment]
As the fix says, you need to pass --devel. Note this will require also installing `flatpak install flathub org.kde.Sdk`.

**Comment by rduivenvoorde** [comment]
Can be closed?
