### ISSUE TITLE
Flatpak application | Missing developer/project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [flathub/org.qgis.qgis#105]
Hello. As noticeable the worth mentioning **developer/project/organisation** name is missing at this application path under https://flathub.org/apps/. Probably as a result it is then dully reported as "_Unknown_" when exhibited by Flatseal '`flatpak run com.github.tchx84.Flatseal`'.

![QGIS_desktop](https://user-images.githubusercontent.com/26058215/117790306-e4768600-b251-11eb-8a15-e2a7e446cd0c.png)

**Comment by aleixpol** [comment]
It needs adding `<developer_name>` in here https://github.com/qgis/QGIS/blob/master/linux/org.qgis.qgis.appdata.xml.in

I'm not sure what would be the right way forward anyway. We could write "QGIS developers" which isn't all that encouraging.

**Comment by Ricky-Tigg** [comment]
_Program_ implicitly refers to _developer_. Then, good examples, similar to _QGIS developers_, illustrating wrong developer name are typical. Here is one more if needed: _The QGIS development team_. Observing the academical naming scheme – _Open Source Geospatial Foundation (OSGeo)_ – is always pertinent.

**Comment by rduivenvoorde** [comment]
@aleixpol Is this still an open question? I cannot find developer_name in org.qgis.qgis.appdata.xml.in?

IF still a question I would take the bibtex example from the qgis site as example: https://qgis.org/en/site/getinvolved/faq/index.html

```
    @Manual{QGIS_software,
      title = {QGIS Geographic Information System},
      author = {{QGIS Development Team}},
      organization = {QGIS Association},
      year = {2022},
      url = {https://www.qgis.org/},
    }
```
would that be enough?

**Comment by Ricky-Tigg** [comment]
This value is part of the application [metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name)[](https://user-images.githubusercontent.com/26058215/118257858-cad67800-b4b7-11eb-8a3e-4a93bc999016.png). I had hoped one of yours will soon figured it out as easily as some others did for other projects. Well, some don't, some do.

**Comment by Ricky-Tigg** [comment]
Ask for help, if not from other developer from user then! You didn't yet fix it when you closed.

![QGIS_Flatseal](https://user-images.githubusercontent.com/26058215/158152962-bac4fb51-12a1-4c30-8c09-8cc97e5ecc83.png)

_The_ value is part of the application [metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name).

**Comment by aleixpol** [comment]
It will be part of the next QGIS release I imagine.
