### ISSUE TITLE
QGIS whitout menus in flatpak

### ISSUE THREAD

**Issue by ncastrog** [flathub/org.qgis.qgis#108]
There are no menus in flatpack installation, distro Alma Linux Linux release 8.4 (Electric Cheetah) 4.18.0-305.el8.x86_64, QGIS 3.16?  LTS
![qgis_bug](https://user-images.githubusercontent.com/4977124/120221739-8875a080-c204-11eb-83e6-abfbeb679a70.png)

Ryzen 5 2400GE
8GB RAM

Thanks.

**Comment by aleixpol** [comment]
This packaging has been tested on GNOME already and it worked. Is there a chance it's an issue with your distribution? I've never heard of Alma Linux so I don't know what they do differently.

**Comment by ncastrog** [comment]
Alma Linux is a fork of Centos 8, RedHat will stop support in december 2021.
There are no text on any menu or button, don even see data sources.
Perhaps expects to have a particular font or font related to kde or Qt?
Thanks

**Comment by aleixpol** [comment]
Do you have the same problem with every Qt-based app?

**Comment by ncastrog** [comment]
Yes, installed KDevelop and is the same behavior.
![kdevelop](https://user-images.githubusercontent.com/4977124/120822298-e31c3e80-c51b-11eb-8401-27d7c44aa979.png)

How I debug that behavior, perhaps is a flatpak problem?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/org.qgis.qgis/issues/108#issuecomment-854797556

Because that behaviour is consistent for every Qt-based application that you have utilised, this is definitely not relevant for specifically [QGIS](http://github.com/flathub/org.qgis.qgis).

**Comment by rduivenvoorde** [comment]
close this one?
