### ISSUE TITLE
System File Dialog is launched behind main QGIS GUI

### ISSUE THREAD

**Issue by palmerj** [flathub/org.qgis.qgis#11]
This doesn't happen in the Debian packaged version that I also have installed on Ubuntu 18.04. See

<img width="1294" alt="dialog" src="https://user-images.githubusercontent.com/580022/46233549-2adf8500-c3c7-11e8-83d9-af0b83c91f30.png">

**Comment by rduivenvoorde** [comment]
@palmerj please provide some more info, it is not clear to me: your are running flatpak on...?

**Comment by Lvaskz** [comment]
I do not know if I'm wrong but I think it's some kind of "portal" ?. The flatpak applications are confined and I think that is a means to access the host. However, other flatpak packages have access to the host without the need for this particular pop-up window.

**Comment by ludvikbrodl** [comment]
Same problem on RedHat using Gnome:

```
NAME="Red Hat Enterprise Linux Client"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Client"
VARIANT_ID="client"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Client 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:client"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

More over, the file explorer does not remember the previous path or the path entered in "Vector Dataset(s)", meaning if I have a long path I have to manually navigate there for every vector source.

**Comment by steko** [comment]
I still encounter this problem on Debian, it makes QGIS almost entirely unusable (apart from the sidebar file browser). Is there any way I can provide more information to help fix this issue?

[qgis-flatpak-debug.log](https://github.com/flathub/org.qgis.qgis/files/3595140/qgis-flatpak-debug.log)

**Comment by TingPing** [comment]
This is something to report against `xdg-desktop-portal-gtk` or `xdg-desktop-portal-kde` depending on which you use.

**Comment by palmerj** [comment]
This is still a user issue for QGIS. Where can this be raised? We are using xdg-desktop-portal-kde. I can only see https://github.com/KDE/xdg-desktop-portal-kde which doesn't have issue turned on.

**Comment by rduivenvoorde** [comment]
@palmerj With me (Debian testing, Wayland) it works fine. I do remember years ago that I had an issue with some gnome setting making my dialogs always modal and centered, which you often do not want in QGIS.. could it be something like this?

**Comment by palmerj** [comment]
I guess but I have no idea what to check for. My simple google search returned nothing. I'm not using Wayland on Ubuntu 18.04 here. This issue doesn't occur when using the same version of QGIS installed via debian package, which makes me think it's flatpak specific.

**Comment by steko** [comment]
For me, the issue was fixed by installing xdg-desktop-portal and xdg-desktop-portal-gtk (this was last year).

https://github.com/flathub/org.qgis.qgis/issues/32

**Comment by palmerj** [comment]
Both of those are already install on my Ubuntu 18.04:

```
$ sudo apt-get install xdg-desktop-portal xdg-desktop-portal-gtk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xdg-desktop-portal is already the newest version (1.7.1-flatpak2~bionic).
xdg-desktop-portal-gtk is already the newest version (1.7.1-flatpak1~bionic).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by aleixpol** [comment]
If the issue is in KDE's portal, you can report it here: https://bugs.kde.org/enter_bug.cgi?product=xdg-desktop-portal-kde

Please write here the bug report so we can get it to the right people.

**Comment by palmerj** [comment]
Done: https://bugs.kde.org/show_bug.cgi?id=422508. Can we please reopen this issue?

**Comment by palmerj** [comment]
This still is not resolved. Can we please reopen the issue until the upstream project fixes the problem?

**Comment by aleixpol** [comment]
Are you running Plasma or GNOME?

**Comment by palmerj** [comment]
Gnome.

**Comment by grulja** [comment]
This is probably a bug in Qt. I thought I already fixed it with https://codereview.qt-project.org/c/qt/qtbase/+/337969, but it looks it needs more work or a problem is somewhere else. I plan to look into it and fix it properly.

**Comment by palmerj** [comment]
Sorry for the noise, I have just updated my egis flatpak to 3.18 and now it seems to be resolved. This is using compiled against Qt | 5.15.2
