### ISSUE TITLE
Qgis 3.16.12 "ModuleNotFoundError: No module named 'ee' " at start

### ISSUE THREAD

**Issue by aConar** [flathub/org.qgis.qgis#123]
I recently installed Qgis flatpack version. After install I installed mmqgis and now every time I run QGIS this error shows up:

ModuleNotFoundError: No module named 'ee' 

I have installed ee:

pip3 freeze | grep ee
ee==0.2

Thanks in advance.

Ale

System info:
lsb_release -a
No LSB modules are available.
Distributor ID: Neon
Description:    KDE neon User - Plasma 25th Anniversary Edition
Release:        20.04
Codename:       focal

Screenshot:

![image](https://user-images.githubusercontent.com/4622888/139945179-d48725ef-e703-4408-85b4-160ca1edb9dc.png)

**Comment by cpba** [comment]
Did you install ee inside the flatpak sandbox?

**Comment by rduivenvoorde** [comment]
See https://github.com/flathub/org.qgis.qgis/#i-need-more-python-modules on how to install extra python the flathub way
