### ISSUE TITLE
Extra python modules

### ISSUE THREAD

**Issue by daniviga** [flathub/org.qgis.qgis#13]
Thanks for the excellent job! There's any way to get extra python modules installed? For example there are some plugins that require `scipy` and `matplotlib` that cannot be loaded because those modules are missing.

**Comment by aleixpol** [comment]
maybe it would be possible to use something like `pip` to get the dependencies and leave them together with the plugins?

**Comment by aleixpol** [comment]
ping?

**Comment by aleixpol** [comment]
Also see #15.

**Comment by daniviga** [comment]
> ping?

I tried to ping upstream but I did not get any solution. I'll met some QGIS core developers in January, I will raise again the issue, let's see!

**Comment by PayasR** [comment]
Just ran into this issue, there needs to be a way to either force using the system python or have pip inside the image that allows more packages to be installed (I needed pandas for trajecTools).. any hope for a solution?

**Comment by aleixpol** [comment]
pip is already inside the image (using --devel), maybe setting the right environment variables would suffice to allow you install the modules and have them found. I'm not an expert in python, help would be welcome.

**Comment by antogerva** [comment]
I found something an interesting workaround. The idea is to enter into the "sandbox-mode" with bash(similar to enter into a docker container):
```bash
flatpak run --command=bash org.qgis.qgis
pip3 install future --user
```
Then press ctrl-D to exit sanbox mode.
Finaly run flatpack again with  `flatpak run org.qgis.qgis`

**Comment by aleixpol** [comment]
Mentioned workaround in the README:
https://github.com/flathub/org.qgis.qgis/blob/master/README.md
