### ISSUE TITLE
Failed to install org.qgis.qgis/x86_64/stable: GPG signatures found, but none are in trusted keyring

### ISSUE THREAD

**Issue by reginaldc** [flathub/org.qgis.qgis#14]
I installed flatpack copying the commands from:
https://flatpak.org/setup/Ubuntu/
after that I did:
flatpak install flathub org.qgis.qgis
I got the error mentioned above
I tried installing other flatpackages and there were no errors.

Regards,

**Comment by aleixpol** [comment]
I think this was due to some issue in flathub that got resolved shortly after.
