### ISSUE TITLE
As the fix says, you need to pass --devel. Note this will require also installing `flatpak install flathub org.kde.Sdk`.

### ISSUE THREAD

**Issue by ThomasStruller** [flathub/org.qgis.qgis#140]
As the fix says, you need to pass --devel. Note this will require also installing `flatpak install flathub org.kde.Sdk`.

_Originally posted by @aleixpol in https://github.com/flathub/org.qgis.qgis/issues/104#issuecomment-907888802_

**Comment by ThomasStruller** [comment]
when I try to install the sdk i get the following response:

thomas@thomas-iMac:~$ flatpak run --devel --command=pip3 org.qgis.qgis install numpy --devel
Fehler: runtime/org.kde.Sdk/x86_64/5.15 ist nicht installiert
thomas@thomas-iMac:~$ flatpak install flathub org.kde.Sdk
Looking for matches…
Similar refs found for ‘org.kde.Sdk’ in remote ‘flathub’ (system):

   1) runtime/org.kde.Sdk/x86_64/5.9
   2) runtime/org.kde.Sdk/x86_64/5.10
   3) runtime/org.kde.Sdk/x86_64/5.11
   4) runtime/org.kde.Sdk/x86_64/5.12
   5) runtime/org.kde.Sdk/x86_64/5.13
   6) runtime/org.kde.Sdk/x86_64/5.14
   7) runtime/org.kde.Sdk/x86_64/5.15
   8) runtime/org.kde.Sdk/x86_64/5.15-21.08
   9) runtime/org.kde.Sdk/x86_64/6.2

which of the sdk's do i have to install?

**Comment by cpba** [comment]
> Fehler: runtime/org.kde.Sdk/x86_64/5.15 ist nicht installiert

Currently it's `runtime/org.kde.Sdk/x86_64/5.15`, it'll change when the manifest is updated, but so will the error message.
