### ISSUE TITLE
Centos 7, error: Unable to allocate instance id

### ISSUE THREAD

**Issue by domaniqs** [flathub/org.qgis.qgis#148]
Hi All,
I'm completely new to QGIS. I installed flatpack on Centos 7 64bit, and when run as root with:
`flatpak run org.qgis.qgis`
everything works OK, however when I run the same command as unprivileged user, I'm getting the error:
`error: Unable to allocate instance id`
Any ideas what to do in order to make QGIS work on Centos 7 on unprivileged user account?
Thanks
Maciej

**Comment by Sinan81** [comment]
I am on Centos7.6, and `flatpak run org.qgis.qgis` runs just fine for unprivilaged user.

**Comment by aleixpol** [comment]
Then let's assume this has been addressed downstream. There's no reason for it not to work as far as I am concerned.
