### ISSUE TITLE
Gtk theme not used when running on Wayland

### ISSUE THREAD

**Issue by lnicola** [flathub/org.qgis.qgis#152]
What the title says.

Wayland:

![image](https://user-images.githubusercontent.com/308347/151845436-42d724f0-2672-4547-a4a4-2628b7354b07.png)

X11:

![image](https://user-images.githubusercontent.com/308347/151845472-ecb3f1e3-cc9f-4818-97ee-32136ce5858a.png)

Gtk apps seem to have no problems with this. My theme is `org.gtk.Gtk3theme.Arc`.

**Comment by aleixpol** [comment]
I've been talking about it with our GTK person and they told me that https://github.com/FedoraQt/QGnomePlatform doesn't integrate other window decorations (which is the only difference between both your windows) as it uses Adwaita.

I'm not sure how fixable this is.

**Comment by lnicola** [comment]
Oh, so my theme actually works except for the window decorations, and those only work when drawn by the server. Got it, thanks.
