### ISSUE TITLE
Please add pdal to have point cloud support

### ISSUE THREAD

**Issue by kikislater** [flathub/org.qgis.qgis#153]
It needs to install pdal then build Qgis with pdal : 
```
-DWITH_PDAL=TRUE
```

**Comment by cpba** [comment]
@kikislater Could you please test the latest build to make sure we did indeed fix this bug?

I originally tested it with a las file I downloaded from usgs, technically it loads without errors but the only thing drawn on screen is a red square. I don't know enough about the subject to tell if that's the intended result.

**Comment by kikislater** [comment]
No worries, I have sufficient data to test, I will on monday and will report here !

**Comment by kikislater** [comment]
A bit slow (more than native building) but it works ! 

![image](https://user-images.githubusercontent.com/13238064/152794904-36c09af9-0e36-4026-8f60-59b6179089e6.png)

**Comment by cpba** [comment]
Thank you, that's great.

@kikislater Is it much slower than usual? Should we open a new bug for it? Do you have any idea what might be causing it?

**Comment by cpba** [comment]
> Much slower and I had one crash more related to intense ram usage. Don't think too ... For me it's the design of flatpak or appimage and others ...

I'm thinking it might be some simple mistake, it might be as easy as building with different options. I'm going to try a few changes but I don't know how to test it once it's done.

@kikislater  Would you be open to testing a new build or at least provide an easy procedure for me to test the performance?

**Comment by kikislater** [comment]
yes but I have no metrics to measure it ! It's just a feeling. And due to this "newest" functionnality in qgis, I don't know if we can code some action to pan and tilt 3d window to check if it's really different.

**Comment by cpba** [comment]
> yes but I have no metrics to measure it ! It's just a feeling. And due to this "newest" functionnality in qgis, I don't know if we can code some action to pan and tilt 3d window to check if it's really different.

I understand, I think it'd still be helpful if you could test this build and report if it runs any better:
https://github.com/flathub/org.qgis.qgis/pull/162#issuecomment-1033090660

**Comment by kikislater** [comment]
I can !
