### ISSUE TITLE
QGIS 3.4

### ISSUE THREAD

**Issue by ccamara** [flathub/org.qgis.qgis#17]
I have installed QGIS following these instructions (https://flathub.org/apps/details/org.qgis.qgis) and apparently only version 3.2 is available, but v 3.4 release notes state that it should be available as flatpak (visit http://changelog.qgis.org/en/qgis/version/3.4-LTR/#flatpak ) . Am I missing something?

**Comment by aleixpol** [comment]
It's building, it failed to build for some reason. On it.
https://flathub.org/builds/#/builders/38/builds/532

**Comment by aleixpol** [comment]
It's been fixed for some days.

**Comment by ccamara** [comment]
True, it works great now. Thanks for your work!
