### ISSUE TITLE
GRASS 7.8.7 is released

### ISSUE THREAD

**Issue by kikislater** [flathub/org.qgis.qgis#176]
GRASS 7.8.7 is released
https://github.com/OSGeo/grass/releases/tag/7.8.7

**Comment by aleixpol** [comment]
Thank you for reporting. Would you maybe be able to create a Pull Request for it?
https://github.com/flathub/org.qgis.qgis/blob/master/org.qgis.qgis.json#L915

**Comment by kikislater** [comment]
Done ! 
https://github.com/flathub/org.qgis.qgis/pull/177
