### ISSUE TITLE
Qgis icon missing

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.qgis.qgis#2]
The icon is missing, see.
![qgis2](https://user-images.githubusercontent.com/29207169/45918919-0aee1580-be4b-11e8-9162-6adcff222681.png)
![qgis1](https://user-images.githubusercontent.com/29207169/45918923-12adba00-be4b-11e8-92d3-54294cd42eac.png)

**Comment by Alexander-Wilms** [comment]
Here's a fix that worked dir KDE w/ Wayland: https://github.com/Subsurface-divelog/subsurface/commit/145853042c7b5d095325520806ea067d0a8285c5

**Comment by Lvaskz** [comment]
the issue remains

**Comment by Lvaskz** [comment]
hi, sorry for asking again, but is this fixed? I have the same problem

**Comment by Alexander-Wilms** [comment]
Adding a call to setDesktopFileName  here [0] might fix it.

[0] https://github.com/qgis/QGIS/blob/e2caf2209aa227e5411572ceab9103f8e387a582/src/app/main.cpp#L820

**Comment by Alexander-Wilms** [comment]
`/var/lib/flatpak/app/org.qgis.qgis/current/active/export/share/` still contains no `icons` directory, though I'm not sure why.

**Comment by Lvaskz** [comment]
Hi, I made VM with linuxmint 19, I noticed that icon from the taskbar shows well, but from app menu not.
In Ubuntu is not shown in both cases.
Can this change from OS DISTRO to distro?
![qgis linuxmint](https://user-images.githubusercontent.com/29207169/46092365-f45cfc80-c171-11e8-86ad-a0a5b362a062.png)

**Comment by Lvaskz** [comment]
I think this issue sould be open, not?

**Comment by aleixpol** [comment]
Let's follow up in #9
