### ISSUE TITLE
ImportError: No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by olea** [flathub/org.qgis.qgis#22]
Hi:

Tried to install [qgis2web](https://github.com/tomchadwin/qgis2web/wiki) plugin but it requires a non-present component PyQt5.QtWebKitWidgets.

QGis data:
```
Referencia: app/org.qgis.qgis/x86_64/stable
ID: org.qgis.qgis
Arquitectura: x86_64
Rama: stable
Origen: flathub
Collection ID: org.flathub.Stable
Date: 2018-11-29 04:28:13 +0000
Subject: Update to qgis 3.4.2 (9ee661f8)
Commit: 249b547613eaaff9d3d8b651d1ffebc499532bfc041868b537d3d231776bf530
Parent: 9f7b5a691c48adeb991276439786a6119f91261b27a27091692565aaa3cde8e0
Localización: /home/olea/.local/share/flatpak/app/org.qgis.qgis/x86_64/stable/249b547613eaaff9d3d8b651d1ffebc499532bfc041868b537d3d231776bf530
Tamaño de la instalación: 899,6 MB
Runtime: org.kde.Platform/x86_64/5.11
Sdk: org.kde.Sdk/x86_64/5.11
```

Just reporting.

Thanks for this awesome work :)

**Comment by aleixpol** [comment]
Hola @olea!
#15 and #16 have a similar problem. Plugins need random different dependencies that we need to get from the flatpak runtime.
In this case it could be just seeing into pyqt to generate the QtWebKitWidgets bindings.

**Comment by aleixpol** [comment]
Simple test:
`flatpak run --command=python org.qgis.qgis -c "from PyQt5.QtWebKitWidgets import *"`
