### ISSUE TITLE
Wrong issues link on flathub

### ISSUE THREAD

**Issue by nicogodet** [flathub/org.qgis.qgis#220]
On https://flathub.org/apps/details/org.qgis.qgis, "Issues" link leads to https://github.com/qgis/QGIS/issues while it should leads first to this repo.

If a bug reported here is indeed a QGIS bug (and not related to flatpak) then you should guide user to report it on QGIS repo.

**Comment by aleixpol** [comment]
To be honest, as an upstream myself from KDE, I don't really understand why people would report to their distro. It never works well. If QGIS developers see that a problem is a packaging one, they know how to reach me.
