### ISSUE TITLE
cannot find proj.db

### ISSUE THREAD

**Issue by mankoff** [flathub/org.qgis.qgis#221]
When running QGIS LTS installed with flatpak:

```bash
$ flatpak run --branch=lts org.qgis.qgis
proj_create_from_database: Cannot find proj.db
```

I have `PROJ_LIB=/usr/share/proj` which is a folder that does exist on the OS level, but,

```bash
$ locate proj.db
```

returns

```
/usr/share/proj/proj.db
/var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/4ee848b99c0b270931a31296b40d0b4b1369de0df67297ae14b0e9046094594c/files/share/proj/proj.db
```

Among many other (miniconda) proj.db files. If I set `PROJ_LIB` to the flatpak version, nothing changes.

**Comment by mankoff** [comment]
With `PROJ_DEBUG=3`, I see

```bash
$ PROJ_DEBUG=3 flatpak run org.qgis.qgis
pj_open_lib(proj.db): call fopen(/home/kdm/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/clean/proj/proj.db) - failed
```

**Comment by aleixpol** [comment]
Right, you shouldn't be passing PROJ_LIB, since it's not present in the flatpak. Is there any reason you need to pass a specific one?

You can try passing `--filesystem=/usr/share/proj` as well, Note /usr shouldn't be accessible otherwise from the flatpak.

**Comment by mankoff** [comment]
If I add `--filesystem=/usr/share/proj` I get a different error message:

```
$ PROJ_DEBUG=3 flatpak --filesystem=/usr/share/proj run 
```

```
pj_open_lib(proj.db): call fopen(/home/kdm/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/clean/proj/proj.db) - failed
proj_create_from_database: Cannot find proj.db
pj_open_lib(proj.db): call fopen(/home/kdm/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/clean/proj/proj.db) - failed
proj_create_from_database: Cannot find proj.db
pj_open_lib(proj.db): call fopen(/home/kdm/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/clean/proj/proj.db) - failed
proj_get_authorities_from_database: Cannot find proj.db
Warning: QLayout::removeWidget: Cannot remove a null widget.

```

**Comment by mankoff** [comment]
Note that there is NO proj.db at `/home/kdm/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/clean/proj/proj.db` or anywhere under `~/.var/app/org.qgis.qgis`.

**Comment by mankoff** [comment]
Is there something I can do to help with this? I'm new to `flatpak`. I viewed all issues and PRs (open and closed) that I thought might be relevant. I don't have any ideas, except that elsewhere it seems people build GDAL with `--with-proj=/path/to/proj` and this project builds it with just `--with-proj`.

**Comment by aleixpol** [comment]
Let's give it a try, could you test the build once it's done?

**Comment by mankoff** [comment]
I would be happy to test. But I'm new to Flatpak and may need some help.

**Comment by aleixpol** [comment]
As you can see on the Pull Request, it didn't build, it seems like using `--with-proj=/app/share/proj/proj.db` isn't the right way to go about it.

We will need to see what's wrong there.

**Comment by aleixpol** [comment]
On my system I'm seeing the following:
```
$ PROJ_DEBUG=3 flatpak run org.qgis.qgis 
pj_open_lib(proj.ini): call fopen(/app/share/proj/proj.ini) - succeeded
pj_open_lib(proj.db): call fopen(/app/share/proj/proj.db) - succeeded
```

Are you sure this is still a problem? This is when running the master branch.

**Comment by mankoff** [comment]
I have LTS, dev, and stable branches. Can you tell me how to install `master`?

**Comment by aleixpol** [comment]
master is stable, sorry.

**Comment by mankoff** [comment]
Yes, it appears to work now. I had `PROJ_LIB` set to something else which was messing things up. Thank you!

**Comment by mankoff** [comment]
Actually, I need `PROJ_LIB` set for other tools that use the non-flatpak installed `proj` in `/usr/share/proj`. Can the flatpak launcher unset or ignore that for the flatpak QGIS?
