### ISSUE TITLE
QGIS in "stable" branch still at version 3.26.1 - QGIS in "lts" branch still at version 3.22.8

### ISSUE THREAD

**Issue by agiudiceandrea** [flathub/org.qgis.qgis#222]
Current QGIS versions are 3.26.2 and 3.22.10.

**Comment by aleixpol** [comment]
https://github.com/flathub/org.qgis.qgis/blob/master/org.qgis.qgis.json#L40 It's 3.26.2

**Comment by agiudiceandrea** [comment]
> https://github.com/flathub/org.qgis.qgis/blob/master/org.qgis.qgis.json#L40 It's 3.26.2

@aleixpol, yes, I now. Anyway in the Flathub repository https://flathub.org/apps/details/org.qgis.qgis is still available only 3.26.1:
![image](https://user-images.githubusercontent.com/16253859/186132332-19841cd4-a489-4b87-b6a1-a136db1fb1fa.png)

```
         ID: org.qgis.qgis
         Ref: app/org.qgis.qgis/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.26.1
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 946,6 MB
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08
      Commit: f192d36ffa9a6d289d7c798cb4d719e7e7e3a914892fa3557dd3c79154c79ed1
      Parent: 249449322bbb0f1dcdbfa7ccb047d421f062dc2650ce8021a03bd98360dd6293
     Subject: Update org.qgis.qgis.json (8de8bb9b)
        Date: 2022-08-10 04:09:24 +0000
```

**Comment by agiudiceandrea** [comment]
@aleixpol, org.qgis.qgis//lts is now at 3.22.10, while org.qgis.qgis//stable is still at 3.26.1.

**Comment by agiudiceandrea** [comment]
org.qgis.qgis//stable is still at 3.26.1 instead of 3.26.2.

**Comment by agiudiceandrea** [comment]
org.qgis.qgis//stable is now at 3.26.2.
