### ISSUE TITLE
make QGIS 3.4.5 (latest LTR) available

### ISSUE THREAD

**Issue by das-g** [flathub/org.qgis.qgis#24]

**Comment by aleixpol** [comment]
Isn't 3.6 acceptable? I'm not sure if there's ways to provide two separate branches and honestly I'd prefer to maintain just the one.

**Comment by Lvaskz** [comment]
Currently the stable version is 3.4.8. I understand the practicality of having only one branch. I think that version 3.6 is not stable, but version 3.4.8 has greater robustness and stability. I think  in this case version 3.4.8 would be a candidate for flatpak especially if you work in companies in which stability is a necessity as in my case.
What do you think?

**Comment by fvguilherme** [comment]
> Isn't 3.6 acceptable? I'm not sure if there's ways to provide two separate branches and honestly I'd prefer to maintain just the one.

Yes, it is. First of all, thank you to pack QGIS as Flatpak. I need QGIS so much and have it in Flatpak is just awesome. In second place, I have one question, the same one I've made to the [AUR maintainer of `qgis-ltr` package](https://aur.archlinux.org/packages/qgis-ltr) and agreeing with @Lvaskz. Why not pack the LTR version of QGIS? Because, theoretically, it is more stable. Specially to business and and Academy environments.

**Comment by das-g** [comment]
Ideally, both, stable (currently 3.4.10) and latest release (currently 3.8.1) should be available, as some might want to try out the latest features while others might need something they can rely on. (And unfortunately, new QGIS versions sometimes actually do break stuff or have previous features just not work anymore.)

I'm pretty sure that flatpack / flathub offers some way to provide multiple versions concurrently.

**Comment by Lvaskz** [comment]
Hi there, any progress with it? Many plugins are not working properly in  develop versión. A stable qgis release Will be better. Or both if Is possible.

**Comment by enzedrailmaps** [comment]
I'm interested in looking at this as current LTRs from package will not run on my systems. However, we are now up to 3.10.8 LTR and 3.14 stable.

**Comment by enzedrailmaps** [comment]
> Isn't 3.6 acceptable? I'm not sure if there's ways to provide two separate branches and honestly I'd prefer to maintain just the one.

If you prefer to maintain just the stable edition is there room for someone else maintaining LTR? They should have almost identical environmental needs but I assume (not knowing the full background of flatpak just yet) each edition has to be built and maintained separately.

**Comment by hristo-mavrodiev** [comment]
+1 to have the stable LTR version. It will be great to have at least Latest and LTR versions. Just adding more branches to the this repo will be enough to solve this. So users could choose to install from a specified commit https://github.com/flatpak/flatpak/issues/3097 .
@aleixpol  Would you please create more branches here or a new repo for qgis-ltr? Latest version become LTR after time, so we already built this versions, just to keep them on different branches.

**Comment by aleixpol** [comment]
There's an LTS branch now.

**Comment by Lvaskz** [comment]
> There's an LTS branch now.

Thanks by that. But It is necessary explain how to access to this lts branch.
I tried from terminal:
flatpak install flathub org.qgis.qgis
that command display options to choose:
1 system
2 user
should select one of them, in this case 2
after that, the terminal display other options:
1 stable 
2 lts 
choose option 2
and wait to install.

How can see this lts version from graphical way ? from flathub? where? No body else know that lts exists, except people involved in this thread

**Comment by aleixpol** [comment]
This is something your tooling should support, for example the the command line client here.

Please report to them: https://github.com/flatpak/flatpak

The one I maintain (Plasma Discover) already shows the different options for you to choose from.
