### ISSUE TITLE
ZSTD compression missing for GeoTIFF raster layers

### ISSUE THREAD

**Issue by agiudiceandrea** [flathub/org.qgis.qgis#254]
ZSTD compressed GeoTIFF raster layers are not correctly imported in latest Flatpak QGIS 3.28.2 on Ubuntu 22.04.

ZSTD compressed GeoTIFF raster layers are correctly imported in QGIS 3.28.2 from official QGIS repository on the same system Ubuntu 22.04 and on Windows.

ZSTD compressed GeoTIFF raster layers were also correctly imported in Flatpak QGIS 3.26.3 on Ubuntu 22.04.

I suppose the issue is due to the commit https://github.com/flathub/org.qgis.qgis/commit/d8eac4de86836f4e24b3f293c71c0a1959d2bcf1 which removed the GDAL config options and in particular the `--with-libtiff=internal` config option. In fact: "ZSTD is available since GDAL 2.3 when using internal libtiff and if GDAL built against libzstd >=1.0, or if built against external libtiff with zstd support." [[1](https://gdal.org/drivers/raster/gtiff.html#creation-options)]

**Comment by dvolgyes** [comment]
@aleixpol are you sure this has been fixed? 
I just tried latest 3.28.3-Firenze, updated minutes ago from flathub, 
and it still doesn't seem to be able to open ZSTD compressed images.

**Comment by aleixpol** [comment]
Reopened as https://github.com/flathub/org.qgis.qgis/issues/268 offers ways to properly test whether the fix works.

**Comment by rafdouglas** [comment]
I confirm that on 3.30.1 ZSTD support is still missing (also tried with the files linked in #268 )

**Comment by dvolgyes** [comment]
I just upgraded to 3.30.3, and it is still not working.
@aleixpol Could this issue get some labels, e.g. 'bug', and some attention? :)

**Comment by jomey** [comment]
Still an issue with 3.34.
Any help needed to figure this one out?

**Comment by aleixpol** [comment]
We are passing -DGDAL_USE_ZSTD=ON to gdal, I don't see how something else would be needed.

**Comment by jomey** [comment]
I wonder if it is because of the build flag
https://github.com/flathub/org.qgis.qgis/blob/565a3226f50288d23e5ee7c892ffced3b8a6bbdd/org.qgis.qgis.json#L289C26-L289C44
which is the flag to [control an externally build libtiff](https://gdal.org/development/building_from_source.html#cmdoption-arg-GDAL_USE_TIFF) in contrast to using the internal one via 
```
-GDAL_USE_TIFF_INTERNAL=ON
```

This I am guessing from the [GDAL docs](https://gdal.org/development/building_from_source.html#cmdoption-arg-GDAL_USE_TIFF_INTERNAL)

**Comment by Hamze-Issa** [comment]
Same Issue with QGIS 3.34 and GDAL 3.4.3 on Ubuntu 22.04.03

**Comment by agiudiceandrea** [comment]
@Hamze-Issa, are you using QGIS 3.34 from Flatpak? (It doesn't seems so, since QGIS from Flatpak uses GDAL 3.8.3).

**Comment by Hamze-Issa** [comment]
Oh I didn't realize this issue is only for Flatpack QGIS my bad, I'll try with the Flatpack one and see how it goes... thanks!

**Comment by Sinan81** [comment]
>We are passing -DGDAL_USE_ZSTD=ON to gdal, I don't see how something else would be needed. 

I ran into the same issue i think. the solution is that external `libtiff` should be built with zstd support. libgeotiff simply relies on libtiff for this.

**Comment by Sinan81** [comment]
in other words, either use gdal's internal libtiff and build gdal with zstd or use external libtiff built with zstd.

**Comment by aleixpol** [comment]
Would anyone be able to test the MR above?

**Comment by Sinan81** [comment]
I believe you still need to compile libtiff (not libgeotiff) with compression formats. geotiff simply relies on libtiff I think.

**Comment by aleixpol** [comment]
libtiff is part of the freedesktop runtime. Without it libgeotiff wouldn't build.

**Comment by Sinan81** [comment]
in that case gdal should be built with internal tiff
```
GDAL_USE_TIFF_INTERNAL=ON
```

**Comment by Sinan81** [comment]
in that case, may be geotiff should also be built internally via `GDAL_USE_GEOTIFF_INTERNAL`

**Comment by Sinan81** [comment]
list of all internal gdal libs available:
```
 * TIFF internal library enabled
 * GEOTIFF internal library enabled
 * PNG internal library enabled
 * JPEG internal library enabled
 * GIF internal library enabled
 * OPENCAD internal library enabled
 * LERC internal library enabled
```

**Comment by aleixpol** [comment]
> in that case gdal should be built with internal tiff

Why?

**Comment by Sinan81** [comment]
> > in that case gdal should be built with internal tiff
> 
> Why?

if libtiff provided by freedesktop runtime isn't build with zstd, then geotiff can't support zstd since it relies on libtiff for this.

**Comment by Sinan81** [comment]
as you might already know `zlib` and `zstd` are two different things, and compiling libgeotiff with `with-zlib` won't provide zstd support.
