### ISSUE TITLE
How to browse GRASS folders?

### ISSUE THREAD

**Issue by mankoff** [flathub/org.qgis.qgis#258]
I'm running the latest flatpak install of qgis and I do see GRASS as an option in the 'processing toolbox'. I can run commands - it appears to be installed and work correctly.

However, when I used to install GRASS outside of  flatpak, I could also navigate GRASS folders in the sidebar and they would have a special icon, and I could examine GRASS mapset variables directly in QGIS. For example, similar to how rasters and PNG and python files here have custom icons in the `Browser`, GRASS also had a small icon. How do I enable this in Flatpak-installed QGIS?

![Screenshot_2023-01-03_075909](https://user-images.githubusercontent.com/145117/210393988-a518ea2c-8e83-48a1-927a-2b66ffc0cca4.png)

**Comment by aleixpol** [comment]
I guess you can try `flatpak run --filesystem=home org.qgis.qgis` to give the process access to your file system.

There's ways to set this setting permanent if that's what you were after.

**Comment by mankoff** [comment]
This issue has reappeared. I'm running qgis 3.28.9, cannot browse GRASS folders.

**Comment by mankoff** [comment]
Based on the changes linked above, I've tried setting `LD_LIBRARY_PATH=/app/lib:/app/grass78/lib:/app/files/grass78/lib` in FlatSeal, but it still does not work.

**Comment by aleixpol** [comment]
Try grass84 instead of 78

This should fix it:  https://github.com/flathub/org.qgis.qgis/pull/862

**Comment by mankoff** [comment]
I tried 78 because `/var/lib/flatpak/app/org.qgis.qgis/current/active/files/grass78/` is a folder that I found.

**Comment by mankoff** [comment]
78 vs. 84 may be because I'm running QGIS 3.28.9 LTS not 3.44.0 stable
