### ISSUE TITLE
build fails with "Unable to locate OpenGL includes" in module gisgrass

### ISSUE THREAD

**Issue by das-g** [flathub/org.qgis.qgis#26]
Trying to build the flatpak from source for QGIS 3.4.4 (branch `aleixpol-3.4.4`, currently at f8c9201eea495cc503c468d369e29751eda11f6a) fails for me:
`flatpak-builder build-dir org.qgis.qgis.json --force-clean`

<details><summary> (expand for full output)

```
checking for location of OpenGL includes... 
checking for GL/gl.h... yes
checking for GL/glu.h... no
configure: error: *** Unable to locate OpenGL includes.
Error: module gisgrass: Child process exited with code 1
```

</summary>

> ```
> 
> (flatpak-builder:7456): Json-WARNING **: 17:14:31.293: Failed to deserialize "modules" property of type "gpointer" for an object of type "BuilderModule"
> Emptying app dir 'build-dir'
> Downloading sources
> Fetching git repo git://git.code.sf.net/p/saga-gis/code, ref refs/tags/release-2-3-1
> remote: Total 0 (delta 0), reused 0 (delta 0)
> Fetching git repo https://github.com/qgis/QGIS.git, ref refs/tags/final-3_4_4
> remote: Enumerating objects: 1, done.
> remote: Counting objects: 100% (1/1), done.
> remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
> Unpacking objects: 100% (1/1), done.
> Starting build of org.qgis.qgis
> Cache hit for proj, skipping build
> Cache hit for geos, skipping build
> Cache hit for spatialindex, skipping build
> Cache hit for freexl, skipping build
> Cache hit for spatialite, skipping build
> Cache hit for postgresql, skipping build
> Cache hit for swig, skipping build
> Cache hit for gdal, skipping build
> Cache hit for qca, skipping build
> Cache hit for qwt, skipping build
> Cache hit for libzip, skipping build
> Cache hit for gsl, skipping build
> Cache hit for sip, skipping build
> Cache hit for pyqt5, skipping build
> Cache hit for qscintilla, skipping build
> Cache hit for qtkeychain, skipping build
> Cache hit for python-six, skipping build
> Cache hit for python-owslib, skipping build
> Cache hit for python-psycopg2, skipping build
> Cache miss, checking out last cache hit
> 
> (flatpak-builder:7456): flatpak-builder-WARNING **: 17:14:36.349: rofiles-fuse not available, doing without
> ========================================================================
> Building module gisgrass in /home/das-g/dev/flathub/org.qgis.qgis/.flatpak-builder/build/gisgrass-3
> ========================================================================
> checking host system type... x86_64-pc-linux-gnu
> checking for gcc... gcc
> checking whether the C compiler (gcc  -L/app/lib ) works... yes
> checking whether the C compiler (gcc  -L/app/lib ) is a cross-compiler... no
> checking whether we are using GNU C... yes
> checking whether gcc accepts -g... yes
> checking for Cygwin environment... no
> checking for mingw32 environment... no
> checking for executable suffix... no
> checking for full floating-point support... yes
> checking for pwd... /usr/bin/pwd
> checking for source directory... /run/build/gisgrass
> checking for build directory... /run/build/gisgrass
> checking for svnversion... no
> checking for MacOSX App... no
> checking for MacOSX architectures... no
> checking for MacOSX SDK... no
> checking how to build libraries... shared
> checking for additional include dirs... 
> checking for additional library dirs... 
> checking for a BSD compatible install... /usr/bin/install -c
> checking for flex... flex
> checking for yywrap in -lfl... no
> checking for bison... bison -y
> checking for ranlib... ranlib
> checking for ar... ar
> checking for env... env
> checking for perl... /usr/bin/perl
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for limits.h... yes
> checking for termio.h... yes
> checking for termios.h... yes
> checking for unistd.h... yes
> checking for values.h... yes
> checking for f2c.h... no
> checking for g2c.h... no
> checking for sys/ioctl.h... yes
> checking for sys/mtio.h... yes
> checking for sys/resource.h... yes
> checking for sys/time.h... yes
> checking for sys/timeb.h... yes
> checking for sys/types.h... yes
> checking for sys/utsname.h... yes
> checking for libintl.h... yes
> checking for iconv.h... yes
> checking for langinfo.h... yes
> checking whether time.h and sys/time.h may both be included... yes
> checking for off_t... yes
> checking for uid_t in sys/types.h... yes
> checking return type of signal handlers... void
> checking for Cygwin environment... no
> checking for ftime... yes
> checking for gethostname... yes
> checking for gettimeofday... yes
> checking for lseek... yes
> checking for nice... yes
> checking for time... yes
> checking for uname... yes
> checking for seteuid... yes
> checking for setpriority... yes
> checking for setreuid... yes
> checking for setruid... no
> checking for drand48... yes
> checking for putenv... yes
> checking for setenv... yes
> checking for nanosleep... yes
> checking whether setpgrp takes no argument... yes
> checking for long long int... yes
> checking for W11... no
> checking for X... libraries , headers 
> checking for dnet_ntoa in -ldnet... no
> checking for dnet_ntoa in -ldnet_stub... no
> checking for gethostbyname... yes
> checking for connect... yes
> checking for remove... yes
> checking for shmat... yes
> checking for IceConnectionNumber in -lICE... yes
> checking for library containing cuserid... none required
> checking for asprintf... yes
> checking for atan... no
> checking for atan in -lm... yes
> checking for dlsym... no
> checking for dlsym in -ldl... yes
> checking for iconv... yes
> checking for socket... yes
> checking for location of zlib includes... 
> checking for zlib.h... yes
> checking for location of zlib library... 
> checking for deflate in -lz... yes
> checking whether to use bzlib... no
> checking for location of External PROJ.4 includes... 
> checking for proj_api.h... yes
> checking External PROJ.4 version... 510
> checking for location of External PROJ.4 library... 
> checking for pj_get_def in -lproj... yes
> checking for location of External PROJ.4 data files... 
> configure: warning: *** External PROJ.4 directory not specified; default will be used
> checking for /usr/share/proj/epsg... no
> configure: warning: *** Unable to locate PROJ data files.
> checking for nad2bin... /app/bin/nad2bin
> checking whether to use regex... yes
> checking for location of regex includes... 
> checking for regex.h... yes
> checking for location of regex library... 
> checking for regcomp... yes
> checking whether to use Readline... yes
> checking for location of Readline includes... 
> checking for readline/readline.h... yes
> checking for readline/history.h... yes
> checking for location of Readline library... 
> checking for readline in -lreadline... yes
> checking for add_history in -lhistory... yes
> checking whether to use GDAL... yes
> checking for gdal-config... /app/bin/gdal-config
> checking whether to use libLAS... no
> checking whether to use PDAL... no
> checking whether to use NetCDF... no
> checking whether to use GEOS... yes
> checking for geos-config... /app/bin/geos-config
> checking for geos_c.h... yes
> checking for initGEOS in -lgeos_c... yes
> checking whether to use TIFF... yes
> checking for location of TIFF includes... 
> checking for tiffio.h... yes
> checking for location of TIFF library... 
> checking for TIFFOpen in -ltiff... yes
> checking whether to use PNG... yes
> checking for location of PNG includes... 
> checking for png.h... yes
> checking for location of PNG library... 
> checking for png_read_image in -lpng... yes
> checking whether to use PostgreSQL... yes
> checking for location of PostgreSQL includes... 
> checking for libpq-fe.h... yes
> checking for location of PostgreSQL library... 
> checking for PQsetdbLogin in -lpq... yes
> checking for PQcmdTuples in -lpq... yes
> checking whether to use MySQL... no
> checking whether to use SQLite... yes
> checking for location of SQLite includes... 
> checking for sqlite3.h... yes
> checking for location of SQLite library... 
> checking for sqlite3_open in -lsqlite3... yes
> checking whether to use OpenGL... yes
> checking for location of OpenGL includes... 
> checking for GL/gl.h... yes
> checking for GL/glu.h... no
> configure: error: *** Unable to locate OpenGL includes.
> Error: module gisgrass: Child process exited with code 1
> 
> ```

</details>

This is on NixOS 18.09:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 18.09.2327.37694c8cc0e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2327.37694c8cc0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

with `flatpak` installed according to my revised setup instructions (flatpak/flatpak.github.io#325), because the current ones didn't work for me. (See flatpak/flatpak.github.io#324.)

**Comment by das-g** [comment]
The same happens on the `master` branch (as of d57c99821aeb34629f0320537179518a24d8a5f1).

**Comment by aleixpol** [comment]
I'm not sure, it certainly worked because we used to serve it in flathub.
Maybe you don't have up to date sdks? Try passing `--install-deps-from=flathub`?

**Comment by aleixpol** [comment]
Just realized, you're probably not including the git submodule.

**Comment by hristo-mavrodiev** [comment]
Do you have any solution, I got the same error when tried to build Qgis3.14.1 on debian 10?
Thanks
