### ISSUE TITLE
QGIS 3.28.2 Flathub error on Linux Mint 21.1

### ISSUE THREAD

**Issue by abm52** [flathub/org.qgis.qgis#260]
When running Flathub through Terminal get this error:
Error: While pulling app/org.qgis.qgis/x86_64/stable from remote flathub: URI https://dl.flathub.org/repo/deltas/yW/g_dR05K4X4C_wjJn1GHpyPoIHAhR00+ogQ+apqC_0/0 exceeded maximum size of 10180561 bytes
error: Failed to install org.qgis.qgis: While pulling app/org.qgis.qgis/x86_64/stable from remote flathub: URI https://dl.flathub.org/repo/deltas/yW/g_dR05K4X4C_wjJn1GHpyPoIHAhR00+ogQ+apqC_0/0 exceeded maximum size of 10180561 bytes
I have also tried through Linux Mint Software Manager and get slightly different error:
While pulling app/org.qgis.qgis/x86_64/lts from remote flathub: Server returned status 404: Not Found
Other software loaded fine from LM Software manager.
Running on PC i7 processor, 16Gb RAM and 1TB SSD
BTW Linux Mint same version loaded fine last week - problem seems to occurred over the weekend?

**Comment by aleixpol** [comment]
Please report this to flathub, there's not much I can do about this from here:
https://github.com/flathub/flathub/issues
