### ISSUE TITLE
flatpak qgis hangs when using file chooser

### ISSUE THREAD

**Issue by jpjoines** [flathub/org.qgis.qgis#263]
I'm using Flatpak QGIS 3.28.3 with Flatpak 1.14.1 on KDE neon 5.26 (Ubuntu 20.04 / Qt 5.15.7 / KDE Plasma 5.26.0).

It is extremely slow to start (>50 s), and when I try to open a QGIS project via the Project menu or Ctrl+O, browsing to the file, and clicking Open, QGIS returns to the main window and hangs with the error:

Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"

Eventually I have to kill QGIS manually.

However, QGIS opens the project as expected if I append the project path to the command to run QGIS:

flatpak run org.qgis.qgis /home/jon/tmp/flatqtest/flatq.qgz

Then, if I try to add a layer via the Layer menu, or Ctrl+Shift+[R|T|V], and then browsing to the file, QGIS again returns to the main window as soon as I click Open and hangs with the same error:

Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"

However, similarly to specifying the project path on the command line, if I paste the path of the file I want to open into the [Raster|Vector] Dataset(s) text box or the File name text box, and click Add, the layer is added as expected.

Here is the terminal output from a run:

$ flatpak -v run org.qgis.qgis /home/jon/tmp/flatqtest/flatq.qgz 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/jon/.local/share/flatpak
F: Opening user flatpak installation at path /home/jon/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/jon/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.15-21.08/2e5a38d200ac5e9c17562bba10b43ac57b5ad4d455d52c16e250d6a03e002e9a/files/lib32 does not exist
F: Cleaning up unused container id 3820072180
F: Cleaning up per-app-ID state for org.qgis.qgis
F: Allocated instance id 993382124
F: Add defaults in dir /org/qgis/qgis/
F: Add locks in dir /org/qgis/qgis/
F: Allowing dri access
F: Allowing host-fs access
F: skipping export for path /usr/libx32 in unsupported prefix
F: Unable to open path /run/media to export read/write: No such file or directory
F: Allowing wayland access
F: Allowing x11 access
F: Running '/usr/libexec/flatpak-bwrap --args 39 /usr/libexec/flatpak-dbus-proxy --args=41'
F: Running '/usr/libexec/flatpak-bwrap --args 39 qgis /home/jon/tmp/flatqtest/flatq.qgz'
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
Warning: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"

The error appears in the terminal as soon as  the file chooser is launched.

**Comment by aleixpol** [comment]
Does it only happen with QGIS from the different flatpak applications? The file dialog is not part of what QGIS offers.

**Comment by jpjoines** [comment]
Good question.  QGIS was the only Flatpak application I had installed.

I just installed Flatpak OBS Studio, and it does have a similar problem.  It is very slow to launch, hangs when I try to browse to a file, and I have to kill it manually.  It never prints any error messages though.

Is the file chooser that QGIS uses provided by org.kde.Platform?  When I install QGIS, I get all of this:
```
$ flatpak list
Name                      Application ID                        Version  Branch      Installation
Mesa                      org.freedesktop.Platform.GL.default   21.3.9   21.08       system
Intel                     org.freedesktop.Platform.VAAPI.Intel           21.08       system
openh264                  org.freedesktop.Platform.openh264     2.1.0    2.0         system
Adwaita theme             org.kde.KStyle.Adwaita                         5.15-21.08  system
KDE Application Platform  org.kde.Platform                               5.15-21.08  system
QGIS Desktop              org.qgis.qgis                         3.28.3   stable      system
``

**Comment by aleixpol** [comment]
No, it's provided by the host system (i.e. your distribution, KDE Neon).

I'd suggest you report there. I notice you are still on KDE Neon 20.04, upgrading to the 22.04 version would probably be a good idea before anything.
