### ISSUE TITLE
zstd compression still doesn't work

### ISSUE THREAD

**Issue by dvolgyes** [flathub/org.qgis.qgis#268]
Hi,

I tried to comment on #254, but it seems it wasn't picked up.
Long story short: I think the ZSTD compression still doesn't work in the latest 3.28.3 version.
I made a pair of test images:
LZW compression (works):
https://drive.google.com/file/d/1iA8Dp3-Ty_AgRQDlHHKw5WIZucQe18s5/view?usp=share_link
ZSTD compression (doesn't open it):
https://drive.google.com/file/d/1Eg0ki6JlxPm_Tb-oNW7DiDuEGfGikqC4/view?usp=share_link

**Comment by aleixpol** [comment]
I've reopened the original issue, sorry I didn't have the time to look into this yet.

I'll copy your message there as it provides useful information.
