### ISSUE TITLE
gdal python import doesn't work

### ISSUE THREAD

**Issue by ghost** [flathub/org.qgis.qgis#28]
Error log
-------------

2019-03-30T10:16:33     INFO    gdal_polygonize.py /home/arjun/indiagisdata/telangana/telangana1.png /tmp/processing_91b4843dc4c543d79fff84e713ceae7b/ad747e23d2b64381933a72ead5e2f968/OUTPUT.shp -8 -b 1 -f "ESRI Shapefile" DN
2019-03-30T10:16:33     INFO    GDAL execution console output
             Traceback (most recent call last):

              File "/app/bin/gdal_polygonize.py", line 36, in

              from osgeo import gdal

             ImportError: No module named osgeo

**Comment by aleixpol** [comment]
Hi,
I'm not able to reproduce the issue. Can you give me some steps as to how you reproduce it?

Also note we released a new version, that could make a difference.

This worked fine for me:
```
$ flatpak run --command=bash org.qgis.qgis 
$ python3
Python 3.7.2 (default, Nov 10 2011, 15:00:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
```

**Comment by arjunaraoc** [comment]
Thanks for investigating. I tried to reproduce on Ver 3.6. I have a  problem trying to run the above in Ubuntu 18.04 with Budgie Desktop

arjun@arjun-945GCM-S2L:~$ flatpak run --command=bash org.qgis.qgis
bash: /etc/profile.d/vte.sh: No such file or directory

My Budgie desktop environment  seems to be having a bug  to run a shell from inside tilix session, which I have to figure out how to fix.

**Comment by aleixpol** [comment]
`flatpak run --command=python org.qgis.qgis -c "from osgeo import gdal"` works just fine.
If there's still another issue, please report specifically.
