### ISSUE TITLE
qgis 3.6.1 SpatiaLite DB is unsupported

### ISSUE THREAD

**Issue by garrettcam** [flathub/org.qgis.qgis#29]
Warning 6: driver SQLite does not support creation option SPATIALITE
ERROR 6: OGR was built without libspatialite support
... sorry, creating/writing any SpatiaLite DB is unsupported

**Comment by aleixpol** [comment]
I'm sorry, could you guide me to reproduce the issue? It will help getting it sorted. SpatiaLite is in the package already, it's just somehow not being found.

**Comment by garrettcam** [comment]
from terminal
`flatpak run org.qgis.qgis`
start new project, add WFS layer from any server eg http://gstore.unm.edu/apps/rgis/datasets/7bbe8af5-029b-4adf-b06c-134f0dd57226/services/ogc/wfs?SERVICE=wfs&REQUEST=GetCapabilities&VERSION=1.0.0
layer is added but error appear on terminal

**Comment by aleixpol** [comment]
Can you please check that it works now after https://github.com/flathub/org.qgis.qgis/pull/90?

Please reopen if it's not.
