### ISSUE TITLE
no screenshot

### ISSUE THREAD

**Issue by eszlari** [flathub/org.qgis.qgis#3]
The upstream appdata doesn't contain any screenshot, so no screenshot on flathub.org either:
https://flathub.org/apps/details/org.qgis.qgis

**Comment by aleixpol** [comment]
This is an issue with the project, I'd suggest to report there. Or send them a patch with the screenshot. They've been super nice and collaborative so far.

**Comment by rduivenvoorde** [comment]
@eszlari please let us know where to put that (link to?) a screenshot. Does it need to be on our github? Or in this repo?

**Comment by aleixpol** [comment]
It needs to be on https://github.com/qgis/QGIS/, on the file at `linux/org.qgis.qgis.appdata.xml.in`.

Something like:
```
  <screenshots>
    <screenshot type="default">
      <image>https://cdn.kde.org/screenshots/kamoso/kamoso.png</image>
    </screenshot>
  </screenshots>
```
More doc:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by rduivenvoorde** [comment]
Ok, done on release-3_2 branch: 
https://github.com/qgis/QGIS/commit/cd0958843defa93a9491293710af5c1143492a8e

Note that in master it was already added (pointing to a screenshot in the website)

**Comment by aleixpol** [comment]
@rduivenvoorde do you know how far is 3.2.4? Or 3.3.0?

**Comment by aleixpol** [comment]
We have 3.4.0, I can see the screenshot now. Thanks!
