### ISSUE TITLE
Qgis 3.6.2 Grass 7 don't work

### ISSUE THREAD

**Issue by vladosam** [flathub/org.qgis.qgis#31]
When i try to run any grass 7 algorithm i get this error:
```
This algorithm cannot be run :-( 
GRASS 7 can't be found on this system from a shell. Please install it or configure your PATH environment variable.
```

**Comment by fvguilherme** [comment]
I have been search a solution to this, too. Is there a way to Flatpak's package talk each other? Sorry, I'm new on Flatpak world.

If this was not possible, the only workaround would be to pack QGIS already with GRASS, just like `qgis-git` [from AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qgis-git#n79).

**Comment by sandrolemosmachado** [comment]
Hi, i am new on flatpak, but the problem reappear
In Qgis there is this definition: /app/lib:/app/grass-7.6.1/lib
However, grass directory is grass76

**Comment by aleixpol** [comment]
Please update, this was solved today, sorry for not seeing your message earlier.
