### ISSUE TITLE
No file dialog (void linux)

### ISSUE THREAD

**Issue by sanderboer** [flathub/org.qgis.qgis#32]
Hi,

On file->save , file->open I get nothing.
No window, no error and qgis operates like I pressed no button. I manage to save to postgres, which is nice. Printing to pdf works, also nice, but exports to pdf or export to svg is no go.
Incidentally, export to dxf does work, but I have to type the filename with a complete path, the file chooser does not react.

If I had to guess it may have to do with the fact that void linux has no systemd.
I tried it in cinnamon and with xmonad, both display no file choosers.
Is there a way I can investigate this further ?

edit: as this is my first time using flatpak, I thought I better check if this behavior is present in other packages, and on first try, notepadqq displays the same erratic behavior, "open file" does nothing, but "open folder" displays a window...

thx.
S

**Comment by sanderboer** [comment]
I am closing this issue myself, but maybe keep it here for further reference:

On void linux, additionally to installing flatpak, one needs to install "xdg-desktop-portal" and/or "xdg-desktop-portal-gtk"

AND THEN RESTART (like it's windows )

**Comment by aleixpol** [comment]
That's an issue in your distro anyway. You should report to them.

**Comment by steko** [comment]
Debian flatpak has the same issue.

**Comment by steko** [comment]
Debian flatpak has the same issue.

**Comment by aleixpol** [comment]
@steko make sure you have xdg-desktop-portal properly set up

**Comment by divergentdave** [comment]
I ran into the same issue on Debian buster. Installing `xdg-desktop-portal-gtk` fixed it for me. (`xdg-desktop-portal` was already previously installed) I would appreciate it if this could be added to the instructions on https://www.qgis.org/en/site/forusers/alldownloads.html#flatpak.

**Comment by aleixpol** [comment]
You will have to ask QGIS maintainers for that, I don't have access to the website.

I would also reach out to Debian packagers and make sure they deliver a good experience in their packaging, which is what you found in the end.

**Comment by eoli3n** [comment]
https://github.com/flathub/org.qgis.qgis/issues/32#issuecomment-488239495
This didn't help here.

**Comment by aleixpol** [comment]
> This didn't help here.

Can you please share your xdg-desktop-portal and xdg-desktop-portal-gtk/kde/wlr output? you should be able to use journalctl to get it.
