### ISSUE TITLE
appstream xml information isn't validating

### ISSUE THREAD

**Issue by aleixpol** [flathub/org.qgis.qgis#35]
See build is failing:
https://flathub.org/builds/#/builders/32/builds/6952

**Comment by aleixpol** [comment]
• tag-invalid           : <metadata_license> is not valid [MIT]
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]

**Comment by basilrabi** [comment]
Your patch in qgis/QGIS#31599 seems to be merged only in the `release-3_8` branch and not in `master`. Thus, the said patch cannot be found on `release-3_10`. Maybe it is one of the reasons for this issue? I have no knowledge in packaging though.

Thank you for the great work @aleixpol .

**Comment by aleixpol** [comment]
This was merged as

```
commit 3371b9cd1531e9f8052478b8e702075c09c40483
Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Date:   Wed Dec 18 22:43:03 2019 +0000

    appstream: include oars metadata in appstream
```
