### ISSUE TITLE
SAGA is not working

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.qgis.qgis#37]
I reported a same issue here https://github.com/flathub/org.qgis.qgis/issues/7
The modules of grass are not installed, I mean  they are shown but when I run it a popup windows appears tell that grass is not installed 
.
Besides saga modules are not working. Every time I made some process with saga I have the same error: Is not possible in every layer.

**Comment by Lvaskz** [comment]
Hi, some progress or commentary ?

**Comment by asitemade4u** [comment]
Same here. Environment = Debian Buster.
I have an error message in the **Messages**/**Processing**:
`Problem with SAGA installation: unsupported SAGA version (found: 7.4.0, required: 2.3.).`

**Comment by aleixpol** [comment]
I don't really know how to solve this as is, here the issue is explained by ubuntu packagers fencing with this same issue.
https://www.mail-archive.com/ubuntu@lists.osgeo.org/msg01601.html

**Comment by Lvaskz** [comment]
> I reported a same issue here #7
> The modules of grass are not installed, I mean they are shown but when I run it a popup windows appears tell that grass is not installed

Now with version 3.10.11 is working well.

**Comment by aleixpol** [comment]
My impression is that this is something unsupported by QGIS as a project. I suggest we bring it up there as this is not something to be solved from packaging:
https://github.com/north-road/qgis-processing-saga-nextgen/issues/9

**Comment by ncdejito** [comment]
I was able to make SAGA appear in the Processing Toolbox by:

1. Checking SAGA version in local flatpak install (e.g. 7.4.0)
```
flatpak run --command=saga_cmd org.qgis.qgis
```
2. Using `locate` to find `SagaAlgorithmProvider.py`. The directory looks a bit like this: 
```
vim /home/ncdejito/.local/share/flatpak/app/org.qgis.qgis/x86_64/lts/0a7c079c95dcdbd6c37bd00180de6c966c9cb089beb2d602f2bbe98b1507d66c/files/share/qgis/python/plugins/processing/algs/saga/SagaAlgorithmProvider.py
```
3. Editing `REQUIRED_VERSION` with `7.4.0`
4. Restarting QGIS
![image](https://user-images.githubusercontent.com/13001116/120525175-6e0d1400-c40a-11eb-9c5b-e79b489f04bc.png)

**Comment by marex0956** [comment]
This solution doesn't work for me (QGIS version 3.24.2 - SAGA version 8.2.0).
