### ISSUE TITLE
question: will you release version 2.18 QGIS? 

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.qgis.qgis#4]
Greetings, will you release version 2.18? The version currently in flathub is incompatible with most plugins

**Comment by aleixpol** [comment]
I am not planning to. I would suggest to make sure the plug-ins are ported as this is the maintained version.

**Comment by stavpup** [comment]
I would also line the QGIS 2 version as a LTS long term release. There are plugins that have not been ported to version 3. It will need to be build only once anyway.
