### ISSUE TITLE
Flatpak of 3.36.0 fails to load with protobuf dependency error

### ISSUE THREAD

**Issue by dllmr** [flathub/org.qgis.qgis#439]
Error as follows: -

qgis: error while loading shared libraries: libprotobuf-lite.so.25.3.0: cannot open shared object file: No such file or directory

Running on up-to-date Arch system, GNOME desktop.

**Comment by dllmr** [comment]
Uninstall and reinstall attempted without success.

**Comment by bvarick** [comment]
I'm getting the same error on Pop!_OS/Gnome/Wayland

**Comment by cyberang3l** [comment]
Tried to build the package with flatpak builder locally and it works with this diff (the main "fix" is that I removed the `"/lib/libprotobuf-lite*"` line):

```diff
diff --git a/org.qgis.qgis.json b/org.qgis.qgis.json
index 0c2118a..eb92c47 100644
--- a/org.qgis.qgis.json
+++ b/org.qgis.qgis.json
@@ -690,12 +690,15 @@
                             "sources": [
                                 {
                                     "type": "archive",
-                                    "url": "https://rsync.osuosl.org/pub/mariadb/mariadb-11.1.3/source/mariadb-11.1.3.tar.gz",
+                                    "url": "https://archive.mariadb.org/mariadb-11.1.3/source/mariadb-11.1.3.tar.gz",
                                     "sha256": "ad3aa6ae478179275ecb28e3ed8a578f2004f084e14409727c0bf04975ace36c",
-                                    "FIXME-x-checker-data": {
+                                    "x-checker-data": {
                                         "type": "anitya",
                                         "project-id": 1887,
-                                        "url-template": "https://rsync.osuosl.org/pub/mariadb/mariadb-$version/source/mariadb-$version.tar.gz",
+                                        "versions": {
+                                          "==": "11.1.3"
+                                        },
+                                        "url-template": "https://archive.mariadb.org/mariadb-$version/source/mariadb-$version.tar.gz",
                                         "stable-only": true
                                     }
                                 }
@@ -1490,8 +1493,7 @@
                     ],
                     "cleanup": [
                         "/bin/protoc*",
-                        "/lib/libprotoc*",
-                        "/lib/libprotobuf-lite*"
+                        "/lib/libprotoc*"
                     ],
                     "sources": [
                         {
```

But another issue I had was that MariaDB 11.1.3 is not available anymore in rsync.osuosl.org. The latest MariaDB 11.1.4 is the only available one, but 11.1.4 was giving me trouble with libfmt (encountered this issue here: https://jira.mariadb.org/browse/MDEV-31963). To work around this, I had to change the mariadb url to use archive.mariadb.org.

For reference, that's how I built the flatpak locally:

```bash
$ git clone https://github.com/flathub/org.qgis.qgis.git
$ git submodule update --init --recursive
$ flatpak install org.flatpak.Builder
$ flatpak run org.flatpak.Builder --force-clean build org.qgis.qgis.json
$ flatpak run org.flatpak.Builder --user --install --force-clean build org.qgis.qgis.json
$ flatpak list | grep qgis
QGIS Development Team   org.qgis.qgis   3.36.0  master  qgis-origin     user
QGIS Development Team   org.qgis.qgis   3.36.0  stable  flathub system
$ flatpak run --branch=stable org.qgis.qgis
qgis: error while loading shared libraries: libprotobuf-lite.so.25.3.0: cannot open shared object file: No such file or directory
$ flatpak run --branch=master org.qgis.qgis
### Starts QGIS 
```

@aleixpol would be nice if we can add some instructions how to build the flatpak locally in the [README](https://github.com/flathub/org.qgis.qgis/blob/master/README.md) under a "Development/Debug" section?

**Comment by aleixpol** [comment]
Building is just `flatpak-builder --disable-updates  --ccache --user --force-clean app org.qgis.qgis.json`, not sure what needs documenting.

Thanks a lot for the research, I issued a PR.

**Comment by cyberang3l** [comment]
Thanks for the quick PR

> not sure what needs documenting.

For someone like me that had only been exposed to installing and using flatpaks, figuring out how to build took some time with trial and error :) Nothing extraordinary, but still, if we had just a few lines in the readme that explain how can one build and run the built flatpak from scratch after cloning this repo, it would be extra helpful :)

**Comment by dllmr** [comment]
Fixed for me too - thanks all :-)

**Comment by polyene** [comment]
The latest update fixed this issue for me. Thank you for taking action so quickly!
