### ISSUE TITLE
After a while qgis no longer starts

### ISSUE THREAD

**Issue by OnTheLink** [flathub/org.qgis.qgis#44]
Hi,

Okay so i am just going to explain what's happening here...
When i install qgis 3.6 everything works fine, it starts, it works, it pretty fast and saving things is also not a problem at first....

But then after a day or two when i boot up the device again, QGIS Desktop just won't start, i don't know what causes this but i did try to run it from the terminal:

**INPUT:** _`sudo flatpak run org.qgis.qgis`_
**OUTPUT:** 
_Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb._

And then exited with the message: _QGIS died on signal -1_

I also tried running using another platform plugin but when i tested with using minimal there is nothing displayed that could be the error, when using minimal it just says: _QGIS died on signal 11_
Could anybody please help me?

The commands i used to install QGIS 3.6:
_`sudo flatpak -y install org.qgis.qgis`_
_`sudo flatpak update --commit=f3e180bb9ddc0cc9fc304e899b7c71405d10db81a8200f3d34dfb6288fec15b9 org.qgis.qgis`_

And here is what i did inside QGIS:
Open QGIS, choose to NOT import older settings (clean start)
Do some QGIS related stuff
Save the files i just made
Close QGIS
Open QGIS to do some more editing
Close QGIS again
reboot

(the first time a reboot may or may not work fine (it can work but most of the time QGIS is just dead after a reboot, i've tried multiple times to reïnstall QGIS and it is really random when the crash appears, so sometimes after the first reboot and sometimes after the 5th...))

**Comment by OnTheLink** [comment]
okay i tried to install it again and now it doesn't even open at all (not even the first time) (it has the QGIS died on signal -1 like before..)

**Comment by OnTheLink** [comment]
I almost forgot to tell you what device i am using:

**_DEVICE INFORMATION:_**

**_> OS: Chrome OS
> MODEL: DELL Chromebook 11 1380
> LINUX: Crostini linux container (LINUX (BÈTA))
> LINUX D: Stretch
> Flatpak V: 1.2.4
> Chrome OS V: Versie 79.0.3945.86 (Official build) beta (64-bits)_**

**Comment by aleixpol** [comment]
There's not much I can do if you force an old version. Can you reproduce this with the current version?
