### ISSUE TITLE
Saga is not working

### ISSUE THREAD

**Issue by kerooksblog** [flathub/org.qgis.qgis#45]
Hi, 

I've installed QGIS 3.10, everything is working but SAGA. In the processing tools there are just GDAL and GRASS, beside the native ones. 
I've tried to install SAGA separately, but I cannot find a way to make it visible on QGIS.

Is it this one just an issue of mine? Have I forgotten something I should have enabled? 

Thanks in advance

**Comment by asitemade4u** [comment]
Same here. I tried to update SAGA on my computer, but was not recognized -- normal, as the SAGA which is not recognized and gets an error message:
`Problem with SAGA installation: unsupported SAGA version (found: 7.4.0, required: 2.3.).`
is the SAGE from within the flatpak.

**Comment by aleixpol** [comment]
This is a duplicate to #37
