### ISSUE TITLE
repo plugins not loaded qgis 3.2

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.qgis.qgis#5]
hi there, with this version qgis 3.2 the repo plugins is not loaded. Every time I reloaded the plugins not appears. In windows the same version works fine. I don't know if this is normal for linux. I made a VM with linuxmint 19 and ubuntu 18.04 and I have the same problem.
The repositories path exists but does not load them

**Comment by aleixpol** [comment]
It's probably because we are not passing `--share=network`. Can you try doing so by running `flatpak run --share=network org.qgis.qgis`? If it works as you expected I'll include it in the recipe so it works out of the box.

**Comment by Lvaskz** [comment]
Yea, with that command works fine !!!
Will you include it soon?

**Comment by aleixpol** [comment]
It will be in the next build that just got triggered.
