### ISSUE TITLE
WFS Provider WARNING - Cannot create temporary SpatiaLite cache

### ISSUE THREAD

**Issue by palmerj** [flathub/org.qgis.qgis#56]
**Describe the bug**
When using the flatpak version of QGIS 3.12.2 on Ubuntu and adding any WFS layer I get the following error:

```
WARNING    Cannot create temporary SpatiaLite cache.
```

I have set the networking cache directory to `~/qgis/cache` and ensure the directory actually has 0777 right to ensure it's not some permissions issue. I note the the following empty directory gets created: `~/.qgis/cache/wfsprovider/pid_2`

I'm wondering if this issue is caused by permissions sandboxing as implemented by flatpak.

**QGIS and OS versions**

QGIS version
3.12.2-Bucuresti
QGIS code revision
8a1fb336
Compiled against Qt
5.14.2
Running against Qt
5.14.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
12.2
SpatiaLite Version
4.3.0a
QWT Version
6.1.4
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
KDE Flatpak runtime
Active python plugins
MetaSearch; 
db_manager; 
processing

This has also been raised upstream at the QGIS project https://github.com/qgis/QGIS/issues/36545

**Comment by palmerj** [comment]
Comment from @rouault over at qgis/QGIS#36545.

> Someone wanting to debug that would have to step into QgsBackgroundCachedSharedData::createCache() (assuming this is possible in this environment) and see where it exists exactly

**Comment by palmerj** [comment]
Looks like the problem is that GDAL is built without spatialite support:

```
Warning 6: driver SQLite does not support creation option SPATIALITE
ERROR 6: OGR was built without libspatialite support
... sorry, creating/writing any SpatiaLite DB is unsupported
```

**Comment by aleixpol** [comment]
This should be fixed as of ebea658547262f16b7d94ffa792b424336e6a867.

**Comment by palmerj** [comment]
I've just retested WFS support after the additional GDAL formats were added. But there are still issues (different ones):

```
2021-03-24T16:24:12     WARNING    SQLite error: no such table: idx_features___spatialite_geometry
             SQL: SELECT "__ogc_fid","__qgis_hexwkb_geom","__qgis_gen_counter", AsBinary("__spatialite_geometry") FROM "features" WHERE ROWID IN (SELECT pkid FROM "idx_features___spatialite_geometry" WHERE xmin = 129.01927429605490261 AND ymin = -53.20561961871506185) AND ("__qgis_gen_counter" 
2021-03-24T16:24:12     WARNING    SQLite error: no such table: idx_features___spatialite_geometry
             SQL: SELECT "__ogc_fid","__qgis_hexwkb_geom","__qgis_gen_counter", AsBinary("__spatialite_geometry") FROM "features" WHERE ROWID IN (SELECT pkid FROM "idx_features___spatialite_geometry" WHERE xmin = 129.01927429605490261 AND ymin = -53.20561961871506185)
```

This means the caching is not working at all with the WFS drivers. I wonder if there is some failure to create temp sqlite database. Is there someway to have a debug version of QGIS?

**Comment by aleixpol** [comment]
> I wonder if there is some failure to create temp sqlite database. Is there someway to have a debug version of QGIS?

You can install org.qgis.qgis.Debug which should have some debug symbols. Would that help?

**Comment by aleixpol** [comment]
Actually, can you create a separate issue?
