### ISSUE TITLE
QGIS Flatpak lacks JPEG compression for GeoTIFF.

### ISSUE THREAD

**Issue by bnordgren** [flathub/org.qgis.qgis#57]
This was initially https://github.com/qgis/QGIS/issues/36662 

Note that on the QGIS page on flathub, the "Issues" link goes to the QGIS project instead of here.

**Feature description.**
Please compile in ability to open GeoTIFFs which use JPEG compression. This is actually in the GDAL library, not QGIS, but the QGIS flatpak contains its own version of GDAL.

**Additional context**
Current flatpak packaging does not include ability to read GEOTIFFs with JPEG compression, which are much smaller.

Using the version of GDAL provided in the flatpak:

```
[📦 org.qgis.qgis multi_plume_frp_rise]$ gdalinfo MOD09.A2017229.1810.006.2017231020109.tif
Warning 1: MOD09.A2017229.1810.006.2017231020109.tif:JPEG compression support is not configured
ERROR 1: Cannot open TIFF file due to missing codec.
gdalinfo failed - unable to open 'MOD09.A2017229.1810.006.2017231020109.tif'.
```

Whereas, on the outside of the flatpak:

```
podman run -ti --rm -v $PWD:/data geographica/gdal2 bash
root@9e909db65fca:/usr/local# cd /data
root@9e909db65fca:/data# gdalinfo MOD09.A2017229.1810.006.2017231020109.tif
Driver: GTiff/GeoTIFF
Files: MOD09.A2017229.1810.006.2017231020109.tif
Size is 8894, 5406
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-123.192745324758206,55.034581073672754)
Pixel Size = (0.004000000000000,-0.004000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=YCbCr JPEG
  INTERLEAVE=PIXEL
  SOURCE_COLOR_SPACE=YCbCr
Corner Coordinates:
Upper Left  (-123.1927453,  55.0345811) (123d11'33.88"W, 55d 2' 4.49"N)
Lower Left  (-123.1927453,  33.4105811) (123d11'33.88"W, 33d24'38.09"N)
Upper Right ( -87.6167453,  55.0345811) ( 87d37' 0.28"W, 55d 2' 4.49"N)
Lower Right ( -87.6167453,  33.4105811) ( 87d37' 0.28"W, 33d24'38.09"N)
Center      (-105.4047453,  44.2225811) (105d24'17.08"W, 44d13'21.29"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
```

**Comment by aleixpol** [comment]
Do you know if there's a missing dependency we've been missing?

**Comment by bnordgren** [comment]
It's been a really long time since I've built this from scratch. From looking at the [current docs](http://www.simplesystems.org/libtiff/build.html), I surmise that the internal libtiff checks the standard locations for [libjpeg](http://www.ijg.org/) and automatically disables JPEG compression if it's not found. 

The [official Dockerfile for GDAL](https://github.com/OSGeo/gdal/blob/master/gdal/docker/ubuntu-full/Dockerfile) installs libjpeg with apt-get. It also builds OpenJpeg, but that's for JPEG2000 support.

If I read your flatpak config right, JPEG2000 isn't enabled either, but there is a common module for OpenJPEG which never gets called? If so, maybe we could make this a two-fer and enable both JPEG compression and the JPEG2000 format. However, I'm not sure I know how to read flatpak configs...

**Comment by bnordgren** [comment]
BTW--the config options for WxWidgets at the bottom of the file includes "--with-libjpeg". Is it actually finding it, or is it failing?

**Comment by bnordgren** [comment]
Tested the build in #58. Works great, thanks!
