### ISSUE TITLE
No 3D support

### ISSUE THREAD

**Issue by palmerj** [flathub/org.qgis.qgis#6]
I think the QGIS cmake option of `-DWITH_3D=TRUE` needs to be passed in

**Comment by aleixpol** [comment]
Ok, adding, how do I test it's working?

**Comment by aleixpol** [comment]
Please give it a go once it updates

**Comment by palmerj** [comment]
Thanks the feature is there. However it crashes my parallels VM as soon as I try to start the new 3D map view. I will test on a real Ubuntu machine to verify if it's the parallels VM 3D support that's the issue.

**Comment by palmerj** [comment]
OK can confirm on the same Ubuntu 18.04 VM that I can get the 3D support working with the debian packaging from https://qgis.org/ubuntu. That version is running QT 5.9.5

**Comment by palmerj** [comment]
On startup of the flatpack I get these OpenGL warnings:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by aleixpol** [comment]
what steps does it take you to get the crash?

**Comment by palmerj** [comment]
1. Start QGIS
2. Add a file to the project by Layer->Data Source Manager. e.g Try this raster https://www.dropbox.com/s/gmrkhjs7ezsns9r/IO.tif?dl=1
3. Select View->New 3D Map View.
4. QGIS crashes

**Comment by palmerj** [comment]
Is there anything I can do to help this along?

**Comment by aleixpol** [comment]
Just tried it, worked here. :/

![screenshot_20181011_220140](https://user-images.githubusercontent.com/1282478/46830556-3bb5d080-cda1-11e8-9e1f-e2072da9d7d6.png)

**Comment by nedrichards** [comment]
@palmerj that sounds like a more general flatpak 3D access issue inside a parallell's VM worth reporting upstream.

**Comment by palmerj** [comment]
Thanks @nedrichards. Upstream raised: https://forum.parallels.com/threads/support-for-opengl-3d-within-ubuntu-host-when-using-flatpaks.345687/
