### ISSUE TITLE
SQLite CRS Database error "no such column: publication_date"

### ISSUE THREAD

**Issue by scubbx** [flathub/org.qgis.qgis#60]
When starting QGIS 3.12.3 from the flatpak repo on a CentOS 7 system, I cannot perform reprojections but always are presented an error in the QGIS UI stating, that there is no reprojection available for the desired CRSs.

On the terminal, even at startup (without doing anything), the following error is recorded:
`proj_create_from_database: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date`

Apparently the column `publication_date` was introduced with proj6. Maybe there is still some old CRS database used?

_(edit:) added screenshot of version info:
![image](https://user-images.githubusercontent.com/1347421/83240412-a8115d80-a199-11ea-9a48-85d1d46d80a4.png)

**Comment by aleixpol** [comment]
Can you please confirm that this is solved in current 3.16?

**Comment by scubbx** [comment]
I can confirm, that at least with the flatpack version QGIS 3.16.3 on Linux Mint 20.1, the problem does not exist anymore.
