### ISSUE TITLE
Warning: Qt: Session management error: None of the authentication protocols specified are supported

### ISSUE THREAD

**Issue by agiudiceandrea** [flathub/org.qgis.qgis#62]
On Ubuntu 20.04 when I start the qgis flatpack I get the following warning:
`Warning: Qt: Session management error: None of the authentication protocols specified are supported`

besides
`Gtk-Message: Failed to load module "canberra-gtk-module"`
https://github.com/flathub/org.qgis.qgis/issues/8

**Comment by wangyubow** [comment]
in the terminal, try this command.  It can be included in .zshrc or .bashrc.
unset SESSION_MANAGER
