### ISSUE TITLE
sslmode value "require" invlaid when SSL support is not compiled in

### ISSUE THREAD

**Issue by GammaGames** [flathub/org.qgis.qgis#65]
I just installed the qgis flatpak and am getting this error:

![image](https://user-images.githubusercontent.com/7832163/86037712-0cc01200-b9fd-11ea-8e43-9892134d3e21.png)

|Name         |Application ID |Version |Branch |Installation|
|-------------|---------------|--------|-------|------------|
|QGIS Desktop |org.qgis.qgis  |3.14.0  |stable |user        |

Might be solvable by using a flag when compiling: https://stackoverflow.com/questions/36186935/postgres-sslmode-value-require-invalid-when-ssl-support-is-not-compiled-using

**Comment by aleixpol** [comment]
Can you give me some more information about it? SSL is definitely available, some module must not be able to find it wherever it's looking.
```
$ flatpak run --command=bash org.qgis.qgis
$ ls /usr/lib/x86_64-linux-gnu/libssl*
/usr/lib/x86_64-linux-gnu/libssl3.so  /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

**Comment by GammaGames** [comment]
I got the same output using both `bash` and `sh`, but here it is:

```sh
$ flatpak run --command=sh org.qgis.qgis
[📦 org.qgis.qgis ~]$ ls -l /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 3 jlieberg jlieberg 380024 Dec 31  1969 /usr/lib/x86_64-linux-gnu/libssl3.so
-rwxr-xr-x 3 jlieberg jlieberg 602136 Dec 31  1969 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

Probably not as helpful, but here's the log output:
![image](https://user-images.githubusercontent.com/7832163/86139040-7ba87400-baac-11ea-9a2d-eef0babcf2d8.png)
