### ISSUE TITLE
Cant install pycurl on ubuntu qgis install

### ISSUE THREAD

**Issue by graial** [flathub/org.qgis.qgis#67]
I've been searching for ages on how to install python modules for ubuntu.  Finally I was able to narrow it down to the python that was installed via flatpak.  

[This page ](https://qgis.org/en/site/forusers/alldownloads.html#flatpak)told me to install using the following command:  
`flatpak run --command=pip3 org.qgis.qgis install pycurl --user`
  
yields:
`__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'`

This was the case when I ran `pip3 install pycurl` natively on my machine.
I was able to resolve it by installing some libcurl and openssl packages 

This time, I can't figure out which package is needed in order for this flatpak install to successfullt install pycurl.  I've tried additional apt packages (such as libcurl4-openssl-dev libssl-dev python3-pycurl) and also searched flatpak.  So far no success.

What can I try next?  I'm not so familiar with flatpak.

**Comment by aleixpol** [comment]
It's working fine now. Can you maybe recheck?

**Comment by aleixpol** [comment]
Please reopen if it still doesn't work.

**Comment by knussear** [comment]
I'm having this same issue. QGIS 3.16.14 installed via flatpak not recognizing any external python modules, and will not install them internally. import pip in the Q python console yields error 
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/knussear/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 32, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/app/share/qgis/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pip'

Same basic error for any module import

**Comment by momaabna** [comment]
> I'm having this same issue. QGIS 3.16.14 installed via flatpak not recognizing any external python modules, and will not install them internally. import pip in the Q python console yields error Traceback (most recent call last): File "/usr/lib/python3.8/code.py", line 90, in runcode exec(code, self.locals) File "", line 1, in File "/home/knussear/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/**init**.py", line 32, in **wrapping_ee_import** _module_ = **builtin_import**(name, *args, **kwargs) File "/app/share/qgis/python/qgis/utils.py", line 793, in _import mod = _builtin_import(name, globals, locals, fromlist, level) ModuleNotFoundError: No module named 'pip'
> 
> Same basic error for any module import

have you found any solution for that

**Comment by knussear** [comment]
No Never did

**Comment by nohal** [comment]
You need to add the `--devel` switch so that the command looks like `flatpak run --devel  --command=pip3 org.qgis.qgis install pycurl --user`

You may also need to `flatpak install runtime/org.kde.Sdk/x86_64/5.15-21.08` if it is missing on your system before the above works.

**Comment by emarcari** [comment]
I'm getting this error: 
error: runtime/org.kde.Sdk/x86_64/5.15-22.08 not installed
when trying to run:
flatpak run --devel --command=pip3 org.qgis.qgis install xdg-desktop-portal  --user
