### ISSUE TITLE
update KDE runtime to 5.15

### ISSUE THREAD

**Issue by eszlari** [flathub/org.qgis.qgis#70]

**Comment by aleixpol** [comment]
Should be the case now, not sure why it wasn't closed automatically.

**Comment by eszlari** [comment]
> Should be the case now, not sure why it wasn't closed automatically.

Because you merged into `branch/stable`, not `master`?

**Comment by aleixpol** [comment]
Could be, I'm not super sure what the role of master is with the new setup... :thinking:

**Comment by eszlari** [comment]
Only the `master` and `beta` branches are built on Flathub.

**Comment by aleixpol** [comment]
Brought it up here: https://discourse.flathub.org/t/keeping-a-stable-and-a-rolling-branch-for-qgis/835/3
