### ISSUE TITLE
Flathub downgrades to 3.10.10

### ISSUE THREAD

**Issue by tomkv** [flathub/org.qgis.qgis#73]
The flathub build has been switched to LTR version, there's no way to run the current (3.14) one, unless the user does downgrade and disables updates.

Please make a branch for the current version and document how to switch between current and LTR versions. Thank you.

**Comment by aleixpol** [comment]
They already are in different branches, I did it wrong the first time, at the moment we're shipping 3.14.16 in the stable branch. We'll be getting an lts branch which is also ready but for some reason it's not being built.

Please reopen if you are seeing a different thing.

**Comment by tomkv** [comment]
It is ok now, can confirm that 3.14 is back.
