### ISSUE TITLE
Python error with latest Flatpak

### ISSUE THREAD

**Issue by asitemade4u** [flathub/org.qgis.qgis#74]
**Describe the bug**
When opening the freshly updated Flatpak version of QGis, I get this Python error:

```
Traceback (most recent call last):
  File "", line 1, in 
  File "/app/share/qgis/python/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/app/share/qgis/python/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'

Python version:
3.8.5 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]

QGIS version:
3.14.16-Pi 'Pi', a235a149

Python path:
['/app/share/qgis/python', '/home/stsinc/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python', '/home/stsinc/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins', '/app/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg', '/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg']
```
It does not prevent me from accessing QGis, qhich seems to be working fine as usual otherwise.

**How to Reproduce**
- Install the Flatpak that was released yesterday (20201025) over the previous version
- Launch QGis

**QGIS and OS versions**

QGIS version | 3.14.16-Pi | QGIS code revision | a235a149
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime

**Comment by jesse-a-reilly** [comment]
Can confirm - having the same issue with latest Flatpak install on Pop!_OS 20.10

```
Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/app/share/qgis/python/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/app/share/qgis/python/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'


Python version:
3.8.5 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]

QGIS version:
3.14.16-Pi 'Pi', a235a149

Python path:
['/app/share/qgis/python', '/home/jesse/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python', '/home/jesse/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins', '/app/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages', '/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg', '/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg']
```

**Comment by Lvaskz** [comment]
same here 
No se pudo cargar el módulo SIP.
El soporte para Python estará deshabilitado.


Traceback (most recent call last):
  File "", line 1, in 
  File "/app/share/qgis/python/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/app/share/qgis/python/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.sip'

**Comment by Lvaskz** [comment]
the version is totally old:

Versión de QGIS | 3.14.16-Pi | Revisión del código de QGIS | a235a149
-- | -- | -- | --
Compilado contra Qt | 5.15.1 | Ejecutándose contra Qt | 5.15.1
Compilado contra GDAL/OGR | 3.0.4 | Ejecutándose contra GDAL/OGR | 3.0.4
Compilado contra GEOS | 3.8.1-CAPI-1.13.3 | Ejecutándose contra GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
Versión del cliente PostgreSQL | 12.2 | Versión de SpatiaLite | 4.3.0a
Versión de QWT | 6.1.5 | Versión de QScintilla2 | 2.11.5
Compilado contra PROJ | 6.3.1 | Ejecutándose contra PROJ | Rel. 6.3.1, February 10th, 2020
Versión del SO | KDE Flatpak runtime

Actually the stable version is 3.10.10 and development version is 3.16

**Comment by Lvaskz** [comment]
many plugins are missed and unaccesibles

**Comment by dragonfly-lover** [comment]
same for me. i posted this issue on the general flatpak issue tracker https://github.com/flatpak/flatpak/issues/3925#issue-730394608

**Comment by asitemade4u** [comment]
Still the same with the latest installment of the Flatpak.
PLEASE do something as all plugins are disabled, which renders QGis useless.
Or, let me know if this is over your abilities and let us switch back to the standard install.

**Comment by Elijah1111** [comment]
There was apparently an update today (31st Oct) that was made to fix the PyQt path errors. This did not fix my issue with the path, perhaps it will help someone else. As a temporary workaround I reverted back to a previous Flatpak version using the commands:

`sudo flatpak update --commit=b3333b5244bc94902b54f1f0e5d8013a6401e8ef60f191d97dc9c27f54378db8 org.qgis.qgis
flatpak update --commit=b3333b5244bc94902b54f1f0e5d8013a6401e8ef60f191d97dc9c27f54378db8 org.qgis.qgis
`

I hope this gets fixed soon.

**Comment by asitemade4u** [comment]
Thank you SO MUCH, this back-pedaling works fine and will allow us to work at full capacity on QGis: plugins are loaded again.

**Comment by jesse-a-reilly** [comment]
Still having issues with the latest 3.16 build. Rolling back to 3.14 works, using:
```
flatpak update --commit=92f9e0a2d4bf298156318072867cd7a71d6310704363052d4ae1b0e6b815c05a org.qgis.qgis
```

**Comment by larsks** [comment]
See #79 and #80 for issues specific to the 3.16 flatpak.

**Comment by asitemade4u** [comment]
The current solution allows for a choice between:
- version 3.10 (LTS)
- and version 3.16 (stable)

But neither are good choices as 3.10 is completey updated and 3.16 still fails on missing Python modules -- and the solution provided does not work.
The best solution here seems to be to roll back to 3.14 as explained [above](https://github.com/flathub/org.qgis.qgis/issues/74#issuecomment-723766131)

**Comment by Lvaskz** [comment]
> But neither are good choices as 3.10 is severely outdated

version QGIS now updated to 3.10.11, no issue with it. At least in my case.

**Comment by dragonfly-lover** [comment]
there's a new build of 3.16 as of today (17 november). can anyone try if it works ootb?

**Comment by olea** [comment]
I've installed it in the system userspace (instead of my usual place), started it and closed without any other action. This is the log:

```
$ flatpak run --system org.qgis.qgis 
Gtk-Message: 10:09:59.318: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:09:59.318: Failed to load module "pk-gtk-module"
Gtk-Message: 10:09:59.318: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:09:59.318: Failed to load module "pk-gtk-module"
Warning: Qt: Session management error: None of the authentication protocols specified are supported
Warning 1: libXML: 0: Element 'SrcSql': This element is not expected.
INFO:rdflib:RDFLib Version: 4.2.2
Warning: QMainWindow::saveState(): 'objectName' not set for QToolBar 0x5595689af6e0 'SentinelHub'

```

version:

```
$ flatpak info --system org.qgis.qgis 

QGIS Desktop - Un Sistema de Información Geográfica libre y código abierto

          ID: org.qgis.qgis
  Referencia: app/org.qgis.qgis/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Version: 3.16.0
     License: GPL-2.0+
      Origen: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1,7 GB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: 3421e2b70e7e488448ee7ec8831a3ed67aeefa93cb603f22d53648ddb5fd6b40
      Parent: f1af8806e9f701768701fd6f25ba9ae84a3cc8e64e3303e03b441c5b0cf0478b
     Subject: Properly point at GIS grass subdirectory (aab5d410)
        Date: 2020-11-17 03:25:50 +0000

```

**Comment by aleixpol** [comment]
As is, I don't see any problems on my system.
I know there's been several which I've struggled but managed to fix over the last few days.

I'd like to leave it like this as is, so please open a new issue if you see a problem (indicating the actual problem on the title).

Sorry for the troubles.
