### ISSUE TITLE
flatpak is missing "pip3" command

### ISSUE THREAD

**Issue by larsks** [flathub/org.qgis.qgis#80]
According to the documentation, one can install additional modules into the flatpak environment by running:

```
flatpak run --command=pip3 org.qgis.qgis install scipy --user
```

But this command results in:

```
bwrap: execvp pip3: No such file or directory
```

**Comment by aleixpol** [comment]
You need to pass `--devel`.

`flatpak run --devel --command=pip3 org.qgis.qgis install scipy --user`

**Comment by asitemade4u** [comment]
I tried too with `--devel` and I get this error message:
```
runtime/org.kde.Sdk/x86_64/5.15 not installed
```

**Comment by aleixpol** [comment]
You will have to install it.

**Comment by aleixpol** [comment]
`flatpak install org.kde.Sdk/x86_64/5.15` that is.

**Comment by asitemade4u** [comment]
Thank you very much, it worked.
