### ISSUE TITLE
qgis 3.16 issue with layers

### ISSUE THREAD

**Issue by kk-qgis** [flathub/org.qgis.qgis#82]
the newest flatpak of qgis 3.16 show not all layers. the layer will be shown if use the command "zoom to layer".
The qgis-version 3.11 is working well.

**Comment by aleixpol** [comment]
Can you please check if it's working now? It wasn't finding GRASS, but it should be addressed now. Please reopen if it's not the case. Having the standard output with the errors that maybe were found would be helpful. Sorry for the issues there.
