### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by Dkrav-UA** [flathub/org.qgis.qgis#87]
When I use command: **_flatpak run --command=pip3 org.qgis.qgis install urllib3 --user_**
I get an error:  **_bwrap: execvp pip3: No such file or directory_**

**Comment by aleixpol** [comment]
As explained in the documentation, to use pip you need to pass `--devel` now.
https://github.com/flathub/org.qgis.qgis/blob/master/README.md
