### ISSUE TITLE
desktop Icon needs transparent background

### ISSUE THREAD

**Issue by palmerj** [flathub/org.qgis.qgis#9]
The flatpack desktop icon doesn't seem to have a transparent background. See comparison with Debian package install:

<img width="71" alt="qgis-icon" src="https://user-images.githubusercontent.com/580022/46105071-27ae9280-c229-11e8-8305-efe6b464f82c.png">

**Comment by aleixpol** [comment]
Do you still see this issue?

**Comment by palmerj** [comment]
Yes I do.
